name: colnitia-onyx-railway

services:
  api_server:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    command: >
      /bin/sh -c "alembic upgrade head &&
      uvicorn onyx.main:app --host 0.0.0.0 --port 8080"
    restart: always
    environment:
      - AUTH_TYPE=basic
      - FILE_STORE_BACKEND=s3
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_PORT=${PGPORT}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - OPENSEARCH_HOST=${OPENSEARCH_HOST}
      - OPENSEARCH_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - ENABLE_OPENSEARCH_INDEXING_FOR_ONYX=true
      - ENABLE_OPENSEARCH_RETRIEVAL_FOR_ONYX=true
      - REDIS_HOST=${REDISHOST}
      - REDIS_PORT=${REDISPORT}
      - REDIS_PASSWORD=${REDISPASSWORD}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_AWS_ACCESS_KEY_ID=${S3_AWS_ACCESS_KEY_ID}
      - S3_AWS_SECRET_ACCESS_KEY=${S3_AWS_SECRET_ACCESS_KEY}

  web_server:
    build:
      context: ../../web
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api_server
    environment:
      - INTERNAL_URL=http://api_server:8080

  background:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    command: >
      /bin/sh -c "/app/scripts/supervisord_entrypoint.sh"
    restart: always
    environment:
      - FILE_STORE_BACKEND=s3
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_PORT=${PGPORT}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - OPENSEARCH_HOST=${OPENSEARCH_HOST}
      - OPENSEARCH_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - ENABLE_OPENSEARCH_INDEXING_FOR_ONYX=true
      - ENABLE_OPENSEARCH_RETRIEVAL_FOR_ONYX=true
      - REDIS_HOST=${REDISHOST}
      - REDIS_PORT=${REDISPORT}
      - REDIS_PASSWORD=${REDISPASSWORD}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_AWS_ACCESS_KEY_ID=${S3_AWS_ACCESS_KEY_ID}
      - S3_AWS_SECRET_ACCESS_KEY=${S3_AWS_SECRET_ACCESS_KEY}
    
  opensearch:
    image: opensearchproject/opensearch:3.4.0
    restart: always
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"  # Lowered lock memory for Railway to 1GB
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data

volumes:
  opensearch-data:
